[project]
name = "DataAnalysisExoplanets"
version = "0.1.0"
description = "The Astronomical Data Analysis for Exoplanets model for the University of Bern Space Sciences & Astronomy masters"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arviz>=1.3.0",
    "astroquery>=0.4.11",
    "corner>=2.3.0",
    "emcee>=3.1.6",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.0",
    "mkslides>=2.0.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "tqdm>=4.70.1",
]
